version: "3.9"
services:
  http_server:
    container_name: httpserver
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: http_server
    volumes:
      - ./:/go/src/github.com/k-akari/otel-example
      - go_mod:/go/pkg/mod
    environment:
      - PORT=9080
      - ENDPOINT_GRPC_SERVER=grpcserver:8080
      - ENDPOINT_JAEGER=http://jaeger:14268/api/traces
    ports:
      - 9080:9080
    networks:
      - jaeger

  grpc_server:
    container_name: grpcserver
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: grpc_server
    volumes:
      - ./:/go/src/github.com/k-akari/otel-example
      - go_mod:/go/pkg/mod
    environment:
      - PORT=8080
      - ENDPOINT_JAEGER=http://jaeger:14268/api/traces
    ports:
      - 8080:8080
    networks:
      - jaeger

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - jaeger

volumes:
  go_mod:

networks:
  jaeger:
