name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'cmd/**'
      - 'internal/**'
      - '.golangci.yml'
      - 'go.mod'
      - 'go.sum'

permissions:
  contents: read

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: "go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # v3.7.1
        with:
          version: v1.58.2
